--- #YAML:1.0
name:               Dancer-Plugin-Auth-Krb5
version:            0.01
abstract:           kerberos authentication for Dancer web apps
author:
    - Hypo Lin <hypo.lin@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Authen::Krb5::Simple:  0.43
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
